### ISSUE TITLE
Language not auto assigned

### ISSUE THREAD

**Issue by ordovice** [ordovice/batocera-switch#10]
Reported by Darknior.  Research and improve

**Comment by Darknior** [comment]
Yes System language for emulator, not the game tab language.

**Comment by ordovice** [comment]
After testing, Yuzu is confirmed to be using the language of the OS/ES.  Will test Ryujinx next to confirm if that is expected behavior

**Comment by ordovice** [comment]
Ryujinx UI language is now set by the OS language.
