### ISSUE TITLE
8BitDo Ultimate Controller - Hotkey Issue

### ISSUE THREAD

**Issue by SHuth78** [ordovice/batocera-switch#120]
**List the Controllers you're using**
Controller used: 8BitDo Ultimate Bluetooth Controller (in 2.4G mode, not actually BT)
Issue: Pressing Select closes Yuzu instantly, as if Hotkey+Start had been pressed. 

**Additional context**
- I suspect it has something to do with the mapping of the "Home" button. 
- Removing the Yuzu-Hotkey binding for "Exit yuzu" stops the issue.
- Trying to configure any of the Yuzu-hotkey bindings results in "Home+Key". It seems like it registers the Home button as being constantly pressed

**logs**
[before-qt-config.ini.log](https://github.com/ordovice/batocera-switch/files/10949575/before-qt-config.ini.log)
[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/10949576/es_launch_stdout.log)
[qt-config.ini.log](https://github.com/ordovice/batocera-switch/files/10949577/qt-config.ini.log)

**Comment by ordovice** [comment]
If select is closing yuzu, make sure you've configured your keys in Batocera properly, as it's seeing select as the "home" key as well.  

The other mappings I'll see what I can do.

**Comment by ordovice** [comment]
This issue happens when you don't run through controller setup in Batocera and isn't an issue with yuzu or the configgen.
