### ISSUE TITLE
RyujinX-Avalonia & RyujinX-LDN Have Black Screen with Sound, Yuzu Crashes on Some Games (Vulkan enabled on Batocera V36)

### ISSUE THREAD

**Issue by batoceragaming** [ordovice/batocera-switch#126]
I just installed the Batocera Switch in Batocera V36 via "Easy Installation"
RyujinX seems to works OK, but I just notice that RyujinX-Avalonia & RyujinX-LDN have Black Screen with Sound.

Is there any work around to solve this issue?

In comparison, I have installed the Batocera-Switch V35 from archive.org (https://archive.org/details/batocera-switch-update-v-35), and then patched the ES feature fix from Batocera Nation (https://www.batoceranation.com/wp-content/uploads/2022/10/Modified-es_feartures-for-Batocera-V36.zip). The RyujinX-Avalonia works perfectly using this method in Batocera V36.

I am using Intel i5-6500T, Intel HD Graphics 530, 16GB of RAM.

I also notice that Yuzu crashes in some games in Batocera V36. While in Batocera V35, Yuzu works perfectly for almost every supported game.

Thanks for your help & your good work :)

**Comment by batoceragaming** [comment]
UPDATE: After changing the Renderer to OpenGL, All Emulators works 100%.

It seems this problem that I mentioned only happen to Vulkan renderer. 

Is it related to Mesa driver or the Update of the Emulators?

**Comment by rfrayer420** [comment]
Try opening one of your flatpaks/ports..... Dont shoot the messenger

**Comment by uureel** [comment]
@batoceragaming it's how it is, opengl has the biggest chance to work on any gpu, can't fix batocera drivers or emus' gpu support, i've added info on that matter to the installer to help troubleshoot it 

@rfrayer420 don't spam
