### ISSUE TITLE
Yuzu & ASUS Gamepad Controls

### ISSUE THREAD

**Issue by funar** [ordovice/batocera-switch#13]
I'm running an ASUS Bluetooth Gamepad on my kiddos' Batocera. The controller works on all platforms (NES, SNES, Genesis, Playstation 1-3, Wii (albeit A&B are backwards), Xbox, MAME, and the list goes on.  However, the button configuration isn't correct when launching a Switch game.

For grins, I launched the yuzu config tool in the file menu, configured the controller as it should be, made a copy of the qt-settings.ini file called "qt-settings.ini.old" exited the configuration, returned to the game menu, and launched a Switch game. The attached file is the diff of the two files.  Something is definitely getting lost in translation:

[qt-settings-diff.txt](https://github.com/ordovice/batocera-switch/files/9493007/qt-settings-diff.txt)

**Comment by ordovice** [comment]
After you launch can you provide the es_stdout_log as well. That will show the SDL mapping and guid your controller is showing from Batocera. 

Can you confirm you’re running the code as it is today and not an old version as well?

**Comment by funar** [comment]
I actually meant to pull that at the same time...
[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/9493035/es_launch_stdout.log)

I can confirm I pulled the master branch and also the yuzu appimage just a few hours ago.

**Comment by ordovice** [comment]
This is definitely a situation of SDL not lining up. I’ll see what I can find.

**Comment by ordovice** [comment]
One thing to validate (even though you may be relying on the button names for other systems), have you ever run through the configure controller Wizard?  

On your controller, for example, B is the East button, but on the SN30/SNES controller, A is the east button which could be causing this.

**Comment by funar** [comment]
I have. I have them mapped to the physical locations of the buttons instead of matching the button labels via the wizard.

**Comment by ordovice** [comment]
That is the issue then. Batocera and all the auto mappings rely on locational buttons. Are you then mapping them to location inside yuzu?

**Comment by ordovice** [comment]
Wait, I think I misunderstood this last night.  So you have east to east, west to west, etc? Are you comfortable with SSH on your system?  If so, can you run evtest and then press the buttons East, South, West, North (in that order) and send me a screenshot or copy the results?

**Comment by ordovice** [comment]
For the record, your SDL config shows the following:
SDL_GAMECONTROLLERCONFIG=05000000050b00000045000031000000,ASUS Gamepad,platform:Linux,b:b3,a:b2,dpdown:h0.4,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,leftstick:b9,dpleft:h0.8,rightshoulder:b7,leftshoulder:b6,righttrigger:a4,rightstick:b10,dpright:h0.2,back:b0,start:b1,dpup:h0.1,y:b5,x:b4,guide:b8,

From SDL wiki, SDL_CONTROLLER_BUTTON_B is always the rightmost button.  On the switch controller, A is the rightmost button, so A should map to B on SDL

Grabbing a few buttons from your diff (the + is the auto generated if I'm understanding your first message correctly)
-player_0_button_a="engine:sdl,guid:05000000050b00000045000031000000,port:0,button:1,pad:0" <-- start:b1
+player_0_button_a="engine:sdl,button:3,guid:05000000050b00000045000031000000,port:0" <-- b:b3

-player_0_button_b="engine:sdl,guid:05000000050b00000045000031000000,port:0,button:0,pad:0" <-- back:b0
+player_0_button_b="engine:sdl,button:2,guid:05000000050b00000045000031000000,port:0" <-- a:b2

Looking at the other auto generated, it's doing something similar to the DS4/DS5 controllers and using a "default" value even though SDL shows another.  And unfortunately it's not the same values as the DS4/DS5.  I wonder if there are other controllers that are doing this as well and use this button mapping.  

Can you run the yuzu configuration for your controller and capture me a screenshot after you hit default?  Also, have you tested all your buttons in game to make sure they're working properly?

**Comment by funar** [comment]
> ... can you run evtest and then press the buttons East, South, West, North (in that order) and send me a screenshot or copy the results?

Attached: [evtest.txt](https://github.com/ordovice/batocera-switch/files/9497540/evtest.txt)

If I configure the controller in Yuzu, it works properly.  Of course, launching "normally" is where it messes up. It's not just the A, B, X, & Y buttons that are messed up.  As you mentioned in the comments about my original diff between the manually generated config in Yuzu and the auto-generated one, pretty much all of the controls are not correct except the D-Pad and 2 analog sticks.  However, pressing down on the analogue sticks are not correct as well.

I'll grab the screenshots later tonight after work.  Wanted to get this one out real quick.  Hopefully it's helpful.

**Comment by funar** [comment]
Here's the requested screenshots...

![autogen](https://user-images.githubusercontent.com/263367/188780705-6e443db7-7c1e-43cc-ad68-87b86dae8e6b.png)
![fixed](https://user-images.githubusercontent.com/263367/188780708-d4e8b7cf-c8b8-4dce-91a9-e90ef2241f97.png)

**Comment by ordovice** [comment]
I saw issues like this with certain 8bitdo controllers in their "B" mode, IIRC.  Essentially it's not a standard mode and some games that interface directly with SDL handle it fine.  does that gamepad have other modes?

**Comment by funar** [comment]
To my knowledge, the controllers do not have any mode switching capability.  It's a pretty basic bluetooth controller, really.

**Comment by ordovice** [comment]
OK, since this is a weird one off, I've added functionality that will allow you to manually configure your controller once and just leave it at that for those with pretty static controller configurations.  

What doesn't make sense, according to the Gamecontroller DB, your controller buttons SHOULD be what it's auto configured as, so there's some other translation happening inside Yuzu for it (which has been driving me bonkers).

**Comment by funar** [comment]
Seems like a reasonable change.  I agree, the likelihood of something funky going on in Yuzu is pretty high. The only other oddity I have with these controllers is with CEMU swapping A+B, & X+Y, but that one is livable, and seem to be fairly common.  I appreciate all your time and attention to this little side case.

**Comment by ordovice** [comment]
Closing as workaround was built into the code
