### ISSUE TITLE
opening yuzu or launching games breaks flatpak

### ISSUE THREAD

**Issue by rfrayer420** [ordovice/batocera-switch#133]
Ive scoured for the cause but it still doesnt change the outcome. every time I open yuzu either to play a game or to change tyhe config it changes permissions on my flatpaks. Version 35 - 36

the fallowing command gets them to work again but having to do this every time i play a game isnt a real solution
chmod -R a+rwx /userdata/saves/flatpak
chmod -R a+rX /userdata/saves/flatpak/binaries
chmod a+rx /userdata /userdata/saves /userdata/saves/flatpak

any way to add that to your launch script to invoke after it stops?

**Comment by uureel** [comment]
fixed, run installer or updater
