### ISSUE TITLE
auto_controller_config vs. yuzu_auto_controller_config & ryu_auto_controller_config features

### ISSUE THREAD

**Issue by funar** [ordovice/batocera-switch#14]
"auto_controller_config" appears in [add_feat_switch.cfg](https://github.com/ordovice/batocera-switch/blob/main/system/configs/emulationstation/add_feat_switch.cfg), but [ryujinxMainlineGenerator.py](https://github.com/ordovice/batocera-switch/blob/main/system/switch/configgen/generators/ryujinx/ryujinxMainlineGenerator.py) and [yuzuMainlineGenerator.py](https://github.com/ordovice/batocera-switch/blob/main/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py) utilize more specific features.

**Comment by ordovice** [comment]
I’ll correct tomorrow.  Only impacts v34 as v35 won’t use this file.

**Comment by ordovice** [comment]
Corrected and re-uploaded.  Download the update and reboot and you should be all set.
