### ISSUE TITLE
Applications config in wrong place, inside a batocera.linux folder

### ISSUE THREAD

**Issue by marcoriesco** [ordovice/batocera-switch#142]
After installing the mod the shortcuts for configuring the emulators that are in Applications are now inside a folder "batocera.linux", clicking on Applications, a folder appears batocera.linux if you enter the folder the configuration shortcuts are there.

Is there any solution to get apps back to normal?

**Comment by drizzt** [comment]
Hi,
you should change inline_limit inside /etc/xdg/menus/batocera-applications.menu from 20 to, at least, 22.

You can do that (ideally, this script should do that in /userdata/system/switch/extra/batocera-switch-startup) by adding this line in /userdata/system/custom.sh:
`sed -i 's/inline_limit="20"/inline_limit="30"/' /etc/xdg/menus/batocera-applications.menu`

or by editing the file directly and save the overlay (https://wiki.batocera.org/modify_the_system_while_it_s_running)...

**Comment by uureel** [comment]
@drizzt thx! 
@marcoriesco fixed
