### ISSUE TITLE
controller works in batocera menu but not in yuzu when starting from the menu

### ISSUE THREAD

**Issue by sitar93** [ordovice/batocera-switch#143]
Easy SMX - ESM-9101 wireless 2.4g

The controller is recognized when starting a game directly from the yuzu app  but doesn't work when starting a game from the emulation station.

Yuzu

The controller is immediatly recognized by batocera and works fine with all the others emulators. The bug is not present when the controller is connected with a cable.
[yuzu_logs.zip](https://github.com/ordovice/batocera-switch/files/11325086/yuzu_logs.zip)

**Comment by ordovice** [comment]
I just added a fix for this controller for yuzu only.  Can you test and let me know?
