### ISSUE TITLE
This should use the standard Batocera generators for yuzu and ryujinx

### ISSUE THREAD

**Issue by drizzt** [ordovice/batocera-switch#145]
Since Batocera includes the generators for yuzu and ryujinx, but they are only disabled (BR2_PACKAGE_BATOCERA_CORES_STILL_COMMERCIALIZED is unset by default) I think this project should use the default generators instead of rewriting it by zero (with different options and behavior, like save directories, etc)

**Comment by ordovice** [comment]
Their generators are basic, don't do any of the button remappings, and are not going to be used.
