### ISSUE TITLE
Controller Button Mapping incorrect

### ISSUE THREAD

**Issue by shanicmeep** [ordovice/batocera-switch#152]
**List the Controllers you're using**
PS5 DualSense Controller

**Yuzu**
Change the emulator to yuzu or yuzu-early-access
Configure your controllers manually
Attach the following files to the bug report
- share\system\logs\es_launch_stdout.log
- share\system\configs\yuzu\before-qt-config.ini
- share\system\configs\yuzu\qt-config.ini

**Additional context**
Keys are out of whack the right analogue stick pressing up will trigger action assigned to L2 Trigger etc. When launching outside of Emulation Station directly via the Yuzu and YuzuEA apps mapping works as expected.

I also updated to latest Batocera 37 Dev build. Unfortunately I didn't stagger updates so cannot confirm if this is an issue with the Yuzu or Batocera update.
[es_launch_stdout.zip](https://github.com/ordovice/batocera-switch/files/11683852/es_launch_stdout.zip)
[before-qt-config.zip](https://github.com/ordovice/batocera-switch/files/11683856/before-qt-config.zip)
[qt-config.zip](https://github.com/ordovice/batocera-switch/files/11683857/qt-config.zip)

**Comment by shanicmeep** [comment]
version 37 unsupported at this stage

**Comment by ordovice** [comment]
@shanicmeep Just for kicks, can you try the latest update?  I had something broken in the controller config section when I added switch anyways.
