### ISSUE TITLE
xBox One Controls

### ISSUE THREAD

**Issue by MeCias** [ordovice/batocera-switch#16]
Hi,
I have an issue in yuzu with the [xbox one controller (bluetooth)](https://wiki.batocera.org/supported_controllers#xbox_core_series_s_series_x_controllers). It works in batocera as expected and in most of the emulators. At least those I usually use. Just in yuzu the buttons get mixed up. A+Y, B+X and start and select keys are swapped. I can set the configuration in yuzu and when I start a game in yuzu it works. Do I start the same game from batocera the buttons are mixed again.

Thanks in advanced..

EDIT
THX
If you need more information please let me know, I am just on Thursday able to though.

**Comment by ordovice** [comment]
Thanks for the report. I will investigate on Monday unless my weekend plans change :)

**Comment by ordovice** [comment]
Did you set the configuration and save it?  I'm not seeing the buttons reversed between the before and running configuration ..

**Comment by ordovice** [comment]
Also, as a note, the letters on the controller will not match.  It's based on button position.  
East on the XB1 controller is B, while on switch it's A, which is the button that's being passed thru.

**Comment by MeCias** [comment]
Thank you for your support.
Yes I did save it and did even create a profile to save it there.
I start the dedicated batocera computer, go to the yuzu configuration and see this layout.

![IMG_20220915_082742](https://user-images.githubusercontent.com/4476171/190333514-4f318ecc-d757-408c-a379-10c09adee757.jpg)

Here all buttons are mixed up west is east, one shoulder button is north, the select button presses select and start together, and so on.

After I press default I see the right layout.

![IMG_20220915_083012](https://user-images.githubusercontent.com/4476171/190334068-14102c28-8026-4479-8295-1a714c3280f1.jpg)

If press OK and I can start directly in yuzu a game without an issue.
If I press OK and exit yuzu and the F1 menu to start the same game from batocera all gets back to the first screenshot again.

I am aware of the button labels not correspond to the layout and that is not an issue for me.

Maybe it is not an issue with yuzu, just I do something wrong?

(Sorry for the screenshot quality, I am not aware how to make a screenshot within the batocera menu)

**Comment by ordovice** [comment]
OK, well your initial report is incorrect, as you need to actually run the reconfiguration like you did in the screenshots before grabbing the configuration files.  I can't diff them if the buttons haven't changed.  
Can you also confirm you have the latest and greatest version of the code?

**Comment by MeCias** [comment]
Apologies for that, I thought I did. Hope that are now the right files.

[before-qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/9574978/before-qt-config.ini.txt)
[es_launch_stdout.log.txt](https://github.com/ordovice/batocera-switch/files/9574979/es_launch_stdout.log.txt)
[qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/9574980/qt-config.ini.txt)

I am using the latest main.

**Comment by MeCias** [comment]
Sooorry.
I did start mario kart over batocera now. Closed it. Went to yuzu configuration did bring the controller back to default  and copied the files.
I noticed that the buttons just get mixed around after I start switch game over batocera. If I do the controller setting directly in yuzu and have a new start of the machine the buttons stay the same as before the restart. So something is happening only when batocera starts yuzu.
 
[before-qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/9575091/before-qt-config.ini.txt)
[es_launch_stdout.log.txt](https://github.com/ordovice/batocera-switch/files/9575092/es_launch_stdout.log.txt)
[qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/9575093/qt-config.ini.txt)

**Comment by MeCias** [comment]
Thanks.
I am would like to use the xbox one because of the rumble function as main controller. I also use a 8bitdo and a wii controller for lightgun games.
Stupid question, how and where do I turn the auto configuration off?

**Comment by MeCias** [comment]
Thanks a lot, that did the trick. Much appreciated.
