### ISSUE TITLE
Joy Cons Gyro disabled.

### ISSUE THREAD

**Issue by antiNT2** [ordovice/batocera-switch#165]
This problem occurs with the Nintendo Switch Joy Cons
All the buttons work, but gyro doesn't unfortunately. It does work when configured manually.
Expected behaviour : Controller gyro working

Also, I guess it would be cool if the joy cons are mapped as actual joy cons instead of pro controller, although I understand that this is low priority.

[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/11777794/es_launch_stdout.log)
[qt-config.zip](https://github.com/ordovice/batocera-switch/files/11777796/qt-config.zip) (Couldn't upload the ini directly)

**Comment by ordovice** [comment]
Once I can afford some joycons I can dig into this process more.  I am working on enabling proper "chose the controller" options to work soon.  

I wonder if enabling motion on non-motion controllers will work without breaking other controllers at which point I'll just turn it on for all controllers.

**Comment by ordovice** [comment]
I've enabled gyro/motion controls on all controllers, so see if that fixes things for the moment.  Once I get joycon support figured out, I'll fix being able to set controllers as joycons.
