### ISSUE TITLE
v35b: Game Launch and DS4 Issues

### ISSUE THREAD

**Issue by CaseyTal** [ordovice/batocera-switch#17]
Hello!

First of all, thank you for this project! It’s great. I just have a few issues.

1) If I set the emulator to Ryujinx on v35 beta, the game launches properly, but the controller is not detected. When I go to Ryujinx config in F1/Applications and click “Configure” for Player 1’s controller, nothing happens. 

2) If the Yuzu emulator is chosen, the Yuzu UI launches, not the game. My DualShock 4 controller is not auto enabled. I have to manually go to configure in Yuzu, then controller and change the drop-down from “Any” to “DualShock 4”. This change does not stay and has to be changed every time Yuzu opens. 

Thanks!!

**Comment by ordovice** [comment]
Please use the issue templates for both Ryujinx and Yuzu and submit as controller issues for each platform with the appropriate files to troubleshoot. Thanks!

**Comment by MeCias** [comment]
Hi ordovice
I can confirm 

> If the Yuzu emulator is chosen, the Yuzu UI launches, not the game.

up to [yuzu 1167](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1167) works fine, all version after are just opening yuzu itself not the game.

Early access works fine, even the newest version.

**Comment by ordovice** [comment]
I’m in the UK for work this week. I’ll give it a check when I get back.

**Comment by ordovice** [comment]
I’m wondering if we are now missing libraries for ldn or the config file changed too much.

**Comment by CaseyTal** [comment]
@ordovice It appears that after updating to the final version of 35 and running "updateyuzu" from the ports menu that the games now launch again properly. 

I'm still having issues with controllers auto detecting. I have to manually go to yuzu-config, choose my controller and disable auto controller config.

**Comment by ordovice** [comment]
Closing as issue 1 is resolved.  Please open a new issue with the template and provide the correct support documentation for the controller detection issues.
