### ISSUE TITLE
Switch install does not show up in applications

### ISSUE THREAD

**Issue by McCrowley** [ordovice/batocera-switch#179]
Hello sorry if I wrote this wrong I have a problem with 
Batocera Switch when I install this

curl -L switch.batocera.pro | bash

It works, but it doesn't show up in the application config.

Can I somehow insert it myself or how do I 
make it in the application?

**Comment by uureel** [comment]
thx for reporting, fixed, was caused by moving ryujinx-ldn to non-avalonia version yesterday (uses different filenames)

**Comment by McCrowley** [comment]
Thank you which file name should I take I'm still a beginner

**Comment by uureel** [comment]
Just run the installer again
