### ISSUE TITLE
V35: Yuzu or Ryujinx does not start within Batocera UI

### ISSUE THREAD

**Issue by Jorgeacb2** [ordovice/batocera-switch#19]
Hello!

First I just want to say, thank you for this amazing project.

I really do not know if I’m doing something wrong, but in V35 it does not let me open yuzu or Ryujinx through the Batocera UI. If I open files and run the application everything is fine, but it does not launch through the UI. My hardware is Intel i5 12th gen / Nvidia RTX 3050. My yuzu version is 1186.

**Comment by CrimsonDevil333333** [comment]
Yes, with v35 from frontend, no game is launching

**Comment by ordovice** [comment]
Have you run updateyuzu from the Ports folder?  Can you provide the es_std logs from \system\logs which should help provide details about why it's not working.

**Comment by ordovice** [comment]
If you upgraded an old version of the switch add-on (or had one of the existing pre-packs, there are files/folders that will break this.
Please Delete the \system\switch folder and install this repo as normal. There are folders in the old install that will break this version.

**Comment by Jorgeacb2** [comment]
I updated yuzu on V34 and it is working. I would guess that it also would work on V35 since I had not ran the updateyuzu from ports. Thank you!

**Comment by CrimsonDevil333333** [comment]
So there was a file corruption issue in the batocera-config-* and so on once I created a new file it is working normally  else it was throwing an error failed to execute child process "/userdata/system/switch/extra/batocera-config-*" even though file seems right and was present there.
