### ISSUE TITLE
Batocera v37 No longer able to launch from emulation station

### ISSUE THREAD

**Issue by Jinyo2** [ordovice/batocera-switch#191]
So I stupidly did a recent update on my machine and switch broke a bit. I was able to get yuzu working again after a manual update so now the games work again, but I am still unable to launch them from the emulation station UI.

**Comment by solomon798** [comment]
I've got the same problem as you.
And I checked the lanncher code. The reason is line 8 - line 13 in the py file "userdata/system/switch/congfiggen/switchlauncher.py":
[
if version.parse(platform.release()) < version.parse("6.1.18"):
    import sys
    sys.path.append('/usr/lib/python3.10/site-packages/configgen/')
else:
    import sys
    sys.path.append('/usr/lib/python3.11/site-packages/configgen/') 
]

The python lib path of different batoceta version is not the same. You can check the actual path of your won system version and modify the "...pythonx.xx...".

**Comment by Wurchi** [comment]
I have the same issue on Batocera v36 but the phython lib path is correct.

killall: evmapy: no process killed
2023-07-25 17:53:29,507 ERROR (switchlauncher.py:599):<module> configgen exception: 
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 597, in <module>
    exitcode = main(args, maxnbplayers)
  File "/userdata/system/switch/configgen/switchlauncher.py", line 109, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
  File "/userdata/system/switch/configgen/switchlauncher.py", line 272, in start_rom
    cmd = generator.generate(system, rom, playersControllers, gameResolution)
  File "/userdata/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py", line 91, in generate
    YuzuMainlineGenerator.writeYuzuConfig(yuzuConfig,beforeyuzuConfig, system, playersControllers)
  File "/userdata/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py", line 420, in writeYuzuConfig
    import sdl2
ModuleNotFoundError: No module named 'sdl2'

Any ohter ideas?

**Comment by ordovice** [comment]
@Wurchi Please reinstall using the curl command as it sounds like your install is incomplete.

**Comment by ordovice** [comment]
@Jinyo2 @solomon798 are you running the latest betas?

**Comment by Wurchi** [comment]
I have installed it twice. First installed via curl over ssh and second time after delete all over the xterm in Batocera. Problem  still exists. What did you mean with last betas?

**Comment by solomon798** [comment]
> @Jinyo2 @solomon798 are you running the latest betas?

Not yet. I also got the sdl problem as you. Maybe we should download the sdl2 lib files for addition, but I'm afraid of causing some unexpected results...
At this momment I use the batocera-switch v35 and it works well in v37.

**Comment by Wurchi** [comment]
Thanks solomon798, i checked v35 and it works also fine at v36.

I wish all a nice day and thanks to all for the help.

**Comment by Jinyo2** [comment]
I am unsure of how to install the latest betas. The latest files I see on git are from last october. I never did the terminal install and did it manually a while back. Not had the chance to mess with it recently.

**Comment by ordovice** [comment]
@Jinyo2 Most of the files have been updated in the past few months.  Are you sure you're installing properly using the curl command?

**Comment by Jinyo2** [comment]
As I said I originally installed manually. I have attempted to install via terminal but it seems to hang up when it begins installing additional files. I have already deleted the old system/switch folder.

**Comment by Jinyo2** [comment]
Scratch that last post it was just slow. However the problem still persists that I can not launch from the emulationstation.

**Comment by ordovice** [comment]
@Jinyo2 What's your latest log error?

**Comment by uureel** [comment]
> As I said I originally installed manually. I have attempted to install via terminal but it seems to hang up when it begins installing additional files. I have already deleted the old system/switch folder.

ipv6 issues with gh on batocera, run these: 

```
wget batocera.pro/app/batocera-switch-installer

chmod 777 batocera-switch-installer

./batocera-switch-installer
```

**Comment by Jinyo2** [comment]
I figured it out. The games that were launching had inside the rom folder key files that I assume were auto  generated. However for some reason every other game did not have this file generated. The files themselves all contained the same thing so I copied and renamed one of them to one of the non launching games. It worked.
