### ISSUE TITLE
Standalone pack for the project

### ISSUE THREAD

**Issue by solomon798** [ordovice/batocera-switch#196]
first thank you for your exellent work!
I've tried to follow the "easy install" but it did not work.
I traced the log and found that was because the source url was in DNS cache pollution, since I live in China.....
It seems that the project includes various source. I tried to write some right source ip in my hosts but still got a lot of wget error.
So I wondering if there is a full-pack standalone version of the project for installing.

**Comment by uureel** [comment]
hi, i've made a local installer package, you can download it from
https://drive.google.com/drive/u/2/folders/1CY4sTAWeSUYDcq6eU-KbjANlYbBXfZPc
or from 
https://batocera.pro/app/batocera-switch-installer

you need to first 
`chmod 777 ./batocera-switch-installer`
then just run it 
`./batocera-switch-installer`

**Comment by solomon798** [comment]
thank you very much!

> hi @solomon798 , i've made a local installer package, you can download it from https://drive.google.com/drive/u/2/folders/1CY4sTAWeSUYDcq6eU-KbjANlYbBXfZPc or from https://batocera.pro/app/batocera-switch-installer
> 
> you need to first `chmod 777 ./batocera-switch-installer` then just run it `./batocera-switch-installer`
