### ISSUE TITLE
v38  XBOX Series Controller 

### ISSUE THREAD

**Issue by trashbus99** [ordovice/batocera-switch#207]
YUZU
V38
XBOX Series Controller via bluetooth (autoconfig not working)
[logs.zip](https://github.com/ordovice/batocera-switch/files/12485873/logs.zip)

**Comment by ordovice** [comment]
Should be resolved in latest commit.  Please update and verify.

**Comment by trashbus99** [comment]
The Analogs/Dpad/Triggers are working correctly however the button mappings are backwards.

Using the switch layout 

gamepad Hard button A (east) is mapped to Soft button B (south)
Hard Button B(south) is mapped to Nothing
Hard button Y (west) is mapped to Soft button A (east)
Hard button X (north) is mapped to soft button Y (west)
Hard R1/Rb is mapped to L1/Lb
Hard L1 is mapped to X (north)
Hard Select is mapped to soft R1/Rb
Hard Start is mapped to soft Select
Hard L3 is mapped to home
Hard R3 is mapped to L3

**Comment by ordovice** [comment]
Can you re-do the auto config, then reconfigure controller logs? 

This is the SDL config from Batocera (highlight on abxy) 
SDL_GAMECONTROLLERCONFIG=050000005e0400008e02000030110000,Xbox Wireless Controller,platform:Linux,**b:b1,a:b0**,dpdown:h0.4,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,leftstick:b9,dpleft:h0.8,rightshoulder:b5,leftshoulder:b4,righttrigger:a5,rightstick:b10,dpright:h0.2,back:b6,start:b7,dpup:h0.1,**y:b3,x:b2**,guide:b8

This is your manual working config
player_0_button_a="engine:sdl,port:0,guid:050000005e0400008e02000030110000,button:1"
player_0_button_b="engine:sdl,port:0,guid:050000005e0400008e02000030110000,button:0"
player_0_button_x="engine:sdl,port:0,guid:050000005e0400008e02000030110000,button:3"
player_0_button_y="engine:sdl,port:0,guid:050000005e0400008e02000030110000,button:2"

Note that Batocera puts button b as East and a as South, and A is East in Yuzu and B is South in Yuzu so these should line up and this should be what the new autoconfig is configuring.  This is really weird.

**Comment by trashbus99** [comment]
ok. using v37 atm if that matters.

**Comment by trashbus99** [comment]
current  works on v38 yuzu.  v37 logs above. Thanks.
