### ISSUE TITLE
Steam deck controllers are incorrectly mapped

### ISSUE THREAD

**Issue by rockmosh** [ordovice/batocera-switch#21]
**List the Controllers you're using**
Steam Deck

**Yuzu**
This is in Yuzu, have not tested Ryujinx

**Additional context**

On steam deck, the controllers are incorrectly mapped when starting a Switch game. For example, the start button immediately shuts down the games. The pad buttons point to different directions. A and Y don't do anything,  X seems to be mapped to A, etc.

I can remap controllers manually but I need to do it every time I start a switch game.

I am on the latest yuzu version, I used your ports script to update it. I also tested this on a completely fresh install of batocera on steam deck.

[es_launch_stderr.log](https://github.com/ordovice/batocera-switch/files/9747927/es_launch_stderr.log)
[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/9747928/es_launch_stdout.log)

**Comment by ragtagsoldier** [comment]
I am having the same issue. I posted in the discord and am waiting on a response. you mention that you can remap manually, how were you able to get into the emulator options on the deck?

**Comment by uureel** [comment]
@rockmosh @ragtagsoldier 
Until desk issues are resolved in future versions, you can try using this simple patch: 

edit the file /userdata/system/configs/emulationstation/es_systems_switch.cfg

& change the line: 
        <command>python /userdata/system/switch/configgen/switchlauncher.py %CONTROLLERSCONFIG% -system %SYSTEM% -rom %ROM%</command>

to: 
        <command>DISPLAY=:0.0 /userdata/system/switch/yuzu.AppImage %ROM%</command>

This will force games to launch using yuzu directly, and so whatever configuration you do in yuzu will not get reset. 
Likewise any configuration you will have to do using the yuzu app directly and not using the ES advanced menu.

@ragtagsoldier If you install the latest version / or use the latest updater, all emulator shortcuts will be added to the F1 -> Applications menu (press F1 on the main Emulationstation screen).

glhf

**Comment by ordovice** [comment]
Rather than changing code why not just use the “disable auto configuration” option that has been present for months now?

**Comment by ordovice** [comment]
Alright, thanks for the files (and my apologies for the delays).  I've committed an initial Steam Deck change.  Test please!
