### ISSUE TITLE
Batocera v38 - 8bitdo SN30 pro BT controller not working with Yuzu when auto controller config is set to "auto"

### ISSUE THREAD

**Issue by prince-rakeem** [ordovice/batocera-switch#217]
8bitdo SN30 pro BT controller
Batocera v38 2023/12/9
switch updater last run 2023/14/9

Prior to running the Switch updater my controller was working as expected. After running the update, my controller no longer works in-game (except hotkey+start to exit).

I have tried yuzu & yuzu-early-access, keeping `auto controller config` set to `auto` and experience the same results with both.

If I go to `yuzu-config > emulation > configure > controls` and change the `input device` from `any` to `xbox 360 controller 0` all the buttons presses are recognized.
If I then choose `ok` and launch a game from within `yuzu-config`, my controller works fine.  If I then exit `yuzu-confi`g and go back to ES launching a game with `auto controller config` set to `off`, my controller is working fine.  Setting `auto controller config` to `auto` causes the controller not to work again.

yuzu `logs` with control cfg set to auto & off are attached.
[auto-cfg controller - yuzu mainline.zip](https://github.com/ordovice/batocera-switch/files/12609075/auto-cfg.controller.-.yuzu.mainline.zip)
[auto-config controller OFF yuzu mainline.zip](https://github.com/ordovice/batocera-switch/files/12609082/auto-config.controller.OFF.yuzu.mainline.zip)

**Comment by ordovice** [comment]
Resolved in latest commit.  Please test and confirm.

**Comment by prince-rakeem** [comment]
I ran the updater today and my BT SN30 pro is now working with yuzu.

Thank you!
