### ISSUE TITLE
Batocera v38 - 8bitdo SN30 pro BT controller not working with Ryujinx when auto controller config is set to "auto"

### ISSUE THREAD

**Issue by prince-rakeem** [ordovice/batocera-switch#218]
8bitdo SN30 pro BT controller
Batocera v38 2023/12/9
switch update latest run 2023/14/9

Prior to running the switch updater my controller was working as expected. After running the update, my controller no longer works in-game (except hotkey+start to exit) with Ryujinx.

I have tried ryujinx-continuous, avalonia and ldn, keeping `auto controller config` set to `auto` and experience the same results across all of them.

If I got to `ryujinx-config > options > settings > input > configure player 1`, `xbox 360 controller` is listed as the `input device`, `controller type` is listed as `pro controller`.  All of the buttons are listed as `unbound`.  It does not allow me to modify any of the buttons or even create a new profile (I choose `add`, give the profile a name, I am unable to assign buttons, I then click `save`, but when I re-enter player 1 config the new profile I created is no longer listed).

ryujinx-continuous logs with control cfg set to `auto` & `off` attached.

[auto configure controller - ryujinx.zip](https://github.com/ordovice/batocera-switch/files/12609603/auto.configure.controller.-.ryujinx.zip)

[auto configure controller - OFF- ryujinx.zip](https://github.com/ordovice/batocera-switch/files/12609643/auto.configure.controller.-.OFF-.ryujinx.zip)

**Comment by ordovice** [comment]
Thanks.  this is a known issue that I'll be looking to address.  They
worked when wired up but apparently 8bitdo did some even more fun stuff
wirelessly (You'll notice there's already a ticket for this with yuzu as
well that I opened, just need time to work on this.)  do they work when you
turn autoconfig off?

**Comment by prince-rakeem** [comment]
With Ryujinx, I tried auto config off, same issue. I also tried to manually configure in Ryujinx-config, but everything is set to unbound and it doesn't seem to want to let me map anything.

For yuzu,I got it working with autoconfig set to off and then setting the input device to Xbox 360 controller in yuzu-config. I also opened an issue for that (#217).

**Comment by ordovice** [comment]
Confirmed that this is a bug in Ryujinx/Batocera and not with the add-on.  Sadly, nothing I can do about it if Ryujinx can't even configure it when manually run.  Issue should be submitted to Ryujinx if you want.
