### ISSUE TITLE
Option to downgrade

### ISSUE THREAD

**Issue by coolwormgit** [ordovice/batocera-switch#224]
This is not an issue, but i updated to latest yuzu and i faced many problem, is there a way to downgrade or to fix something in Ports to downlograde versions?

Thanks

**Comment by uureel** [comment]
there is, you can pick any version for any emulator by editing this file: 
/userdata/system/switch/CONFIG.txt 

![image](https://github.com/ordovice/batocera-switch/assets/116395185/e29ab20d-f8b0-4483-9ee4-d5cfefca68fa)

**Comment by coolwormgit** [comment]
Thanks!! this is great 👍👍😃
