### ISSUE TITLE
custom.sh depreceated in Batocera v38

### ISSUE THREAD

**Issue by cyberpunkbln** [ordovice/batocera-switch#267]
Hello,

/userdata/system/custom.sh will not be loaded at system startup. I must this script once manually start. After start custom.sh all functioned well. Must it every start run or is once start okay? I have it called once and all functioned without call this script after a reboot again. At the moment i can put this in my own autostart mechanism so there it start with every systemstart of batocera, when this is needed.

thx

**Comment by uureel** [comment]
hi, the script will be moved to services once custom.sh does get removed, it's kept in custom.sh which still works fine so far for backwards compatibility
