### ISSUE TITLE
Script has deleted the Yuzu appimage 

### ISSUE THREAD

**Issue by KruyKaze** [ordovice/batocera-switch#269]
Same as title. I no longer see Yuzu mainline or early access in
 /userdata/system/switch/
Anyway I can fix this?
Thanks

**Comment by isamudaison** [comment]
I'm seeing a similar issue. While yuzu is still actually installed, runnign any game results in this error:

```
/userdata/system/switch/extra/yuzu/yuzu: error while loading shared libraries: libQt5Multimedia.so.5: cannot open shared object file: No such file or directory
```

Ryujinx works fine.

**Comment by isamudaison** [comment]
v39 with '+' -> :+1:

**Comment by uureel** [comment]
issue out of date
