### ISSUE TITLE
yuzu-mirror download link  and yuzu's rebirth project suyu

### ISSUE THREAD

**Issue by lrf739146825** [ordovice/batocera-switch#277]
batocera-switch-updater.sh

link_yuzu=https://archive.org/download/yuzu-windows-msvc-20240304-
537296095_20240305_1340/Linux/yuzu-mainline-20240304-537296095.AppImage

Project : https://github.com/yuzu-mirror/yuzu-downloads
link_yuzu=https://github.com/yuzu-mirror/yuzu-downloads/raw/main/Mainline%20Build%20-%20537296095%20\(2024-03-04\)/yuzu-mainline-20240304-537296095.AppImage

-------------------------------------------------
Yuzu's rebirth project
https://github.com/suyu-emu/suyu

**Comment by uureel** [comment]
thx, added

**Comment by lrf739146825** [comment]
I got the link from this way.&nbsp; Right-click ，then copy the link。




https://github.com/yuzu-mirror/yuzu-downloads/raw/main/Mainline%20Build%20-%20537296095%20(2024-03-04)/yuzu-mainline-20240304-537296095.AppImage&nbsp;


The link will redirect to the real path :&nbsp;


https://raw.githubusercontent.com/yuzu-mirror/yuzu-downloads/main/Mainline%20Build%20-%20537296095%20(2024-03-04)/yuzu-mainline-20240304-537296095.AppImage


"\" was added to the front of the "(" and ")" to fix curl command&nbsp; error.


link_yuzu=https://raw.githubusercontent.com/yuzu-mirror/yuzu-downloads/main/Mainline%20Build%20-%20537296095%20\(2024-03-04\)/yuzu-mainline-20240304-537296095.AppImage


&nbsp;


溅の小孩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月5日(星期五) 凌晨3:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ordovice/batocera-switch] yuzu-mirror download link  and yuzu&#39;s rebirth project suyu (Issue #277)














 
thx, added

**Comment by lrf739146825** [comment]
I got the link from this way. Right-click ,then copy the link。

![picture01](https://github.com/ordovice/batocera-switch/assets/43704813/d1bcc66a-8c0e-483f-b5dc-f0253fd6bf9b)

https://github.com/yuzu-mirror/yuzu-downloads/raw/main/Mainline%20Build%20-%20537296095%20(2024-03-04)/yuzu-mainline-20240304-537296095.AppImage

The link will redirect to the real path：
https://raw.githubusercontent.com/yuzu-mirror/yuzu-downloads/main/Mainline%20Build%20-%20537296095%20(2024-03-04)/yuzu-mainline-20240304-537296095.AppImage

“\” was added to the front of the "(" and ")" to fix curl command  error.

link_yuzu=https://raw.githubusercontent.com/yuzu-mirror/yuzu-downloads/main/Mainline%20Build%20-%20537296095%20\(2024-03-04\)/yuzu-mainline-20240304-537296095.AppImage
