### ISSUE TITLE
Ryujinx >=1.1.383 sdl2 update demands action re controllers

### ISSUE THREAD

**Issue by uureel** [ordovice/batocera-switch#42]
Current status: ryu controllers are being borked by generator on v35 and v36
-----------------------
1.1.383 - 2022-11-24
Fixed:

    chore: Update Ryujinx.SDL2-CS to 2.24.2.
        May improve controller compatibility or sound issues in some games.
            **_Controller bindings may need to be reconfigured after this update._**

**Comment by uureel** [comment]
Some details: 
- First run of new Ava builds defaults input to "All Keyboards" instead of Controller (1 is present) 
- First (the default) choice of Controller picks "JoyCon Pair" (instead of Pro Controller?)

Upon saving input config in F1 Ava, and then launching a game from ES (with "Auto controller config = Auto"): 
-- No controls

logs attached

[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/10096718/es_launch_stdout.log)
[Config-json.txt](https://github.com/ordovice/batocera-switch/files/10096720/Config-json.txt)
[BeforeRyu-json.txt](https://github.com/ordovice/batocera-switch/files/10096721/BeforeRyu-json.txt)
[Ava-BeforeES-Config-json.txt](https://github.com/ordovice/batocera-switch/files/10096723/Ava-BeforeES-Config-json.txt)

**Comment by ordovice** [comment]
As we've determined, yuzu is going to be broken as well.  You're locking the updater version and then I'll spend some time digging into the SDL code/calculations to see if I can determine the fixes.

**Comment by ordovice** [comment]
Alright, Ryujinx works for a majority of controllers now with the latest release, we just need to build out the mapping database :-)
