### ISSUE TITLE
no controller activity detected

### ISSUE THREAD

**Issue by MadTyres** [ordovice/batocera-switch#5]
i cannot use any controller to get past the intro screen in any game

doesn't seem like the controllers are registered by yuzu properly, or the refactor you did 5 days ago somehow changed this functionality :) 

Also, do i need to run the custom.sh script to make the Yuzu/Ryujinx option available in advanced game options? :)

Great work on this btw, love the project

**Comment by ordovice** [comment]
I'm still mid-refactor .. for now I'd use one of the pre-packaged solutions until I get all the kinks out .. Right now it relies on Yuzu autodetecting the controller and mapping it properly.  Additionally, if you've used the other pre-packaged solutions out there, you might still have an evmapy file causing issues too.

**Comment by MadTyres** [comment]
havent used other prepackaged solutions, but an earlier version of this repository :)
Though you might be right on the evmapy... will look around

**Comment by ordovice** [comment]
Just letting you know I'm not dead and I'm now hopefully working on a proper v34 version.

**Comment by ordovice** [comment]
Can you test the version for v34 code now.

**Comment by ordovice** [comment]
Closing this as most of the controller bugs have been worked out of the yuzu codebase.  Ryujinx options were never up previously, but exist now.  Soon all DS4/DS5 issues should be worked out.
