### ISSUE TITLE
[v36 beta]  Neither Ryujinx nor Yuzu start from Emulation Station

### ISSUE THREAD

**Issue by prosolis** [ordovice/batocera-switch#51]
Hi there!

I know v36 beta was not tested (6.x kernel Zen4 support), so I'm only looking for some pointers on where to look to start troubleshooting the issues I'm experiencing. Yuzu appears to have an issue detecting either OpenGL or Vulkan support on the GPU (AMD 6900 XT). Ryujinx runs great (tested a few games) when executed from the file manager, but not Emulation Station. Any advice is appreciated. Thank you for your time.

**Comment by ordovice** [comment]
v36 launch was corrected several commits ago.  Update the launcher code using the updater.  Additionally, the Yuzu issue is an issue with Yuzu, and not part of this codebase.
