### ISSUE TITLE
Switch controller mapping "out of the box" is wrong on latest v36 batocera

### ISSUE THREAD

**Issue by rockmosh** [ordovice/batocera-switch#61]
I'm using latest Yuzu and Batocera v36 beta on Steam Deck.

Controller is incorrectly mapped "out of the box". For example, the start button causes the game to immediately exit. Other examples are the A, B buttons incorrectly mapped, as well as the D-Pad.  
If I disable Controller Auto-config and configure the controller myself, things work as expected.

Attached is a zip file with all logs requested. Please note, the attached logs were taken after I tested the "out of the box" controller mapping which is wrong.

**Additional context**
I'm on latest Batocera v36, as of 11-Dec-2022.
After I upgraded to the latest beta, I used the script indicated in the github which was created by ureel to (re)install switch.

[control_logs.zip](https://github.com/ordovice/batocera-switch/files/10204152/control_logs.zip)

**Comment by rockmosh** [comment]
Attached here please find the same logs but this time after I disabled controller auto-config, manually fixed the controller mapping and then started the same game.
[control_after_manual_fix_logs.zip](https://github.com/ordovice/batocera-switch/files/10204201/control_after_manual_fix_logs.zip)

**Comment by ordovice** [comment]
Thanks for submitting.  I've gone ahead and added the mapping to the table and it should work now.  Test and let me know!

**Comment by ryanrudolfoba** [comment]
hi there. Im also using a Steam Deck and on latest batocera stable v36. There seems to still be a issue with yuzu controls.

The left analog stick doesnt work. and the left shoulder button ZL once pressed it behaves like the UP button is pressed all the time.

**Comment by ordovice** [comment]
@ryanrudolfoba can you follow the ticket submission process for your unique controller situation.  It makes tracking the fixes/changes easier.  

@rockmosh did the controller mapping fix your issues?

**Comment by ordovice** [comment]
@rockmosh I'm closing this as I've migrated this to the new mapping file.  @ryanrudolfoba please submit your own issue and files and I'll work on getting it added to the mapping file.
