### ISSUE TITLE
xbox series S|X 1904 controllers (over bluetooth) v35

### ISSUE THREAD

**Issue by trashbus99** [ordovice/batocera-switch#62]
**List the Controllers you're using**

**Yuzu**
Change the emulator to yuzu or yuzu-early-access
Configure your controllers manually
Attach the following files to the bug report
- share\system\logs\es_launch_stdout.log
- share\system\configs\yuzu\before-qt-config.ini
- share\system\configs\yuzu\qt-config.ini

**Additional context**
Add any other context about the problem here, such as "keys are reversed" or anything else you can provide

mappings are messed up (e.g. r1 i
[before-qt-config.txt](https://github.com/ordovice/batocera-switch/files/10252359/before-qt-config.txt)
s start, etc)
[qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/10252358/qt-config.ini.txt)

[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/10252357/es_launch_stdout.log)

**Comment by ordovice** [comment]
@trashbus99 Did you actually reconfigure the controllers and then exit out of the emulator?  The config files literally show the same keymappings for before and after.

**Comment by trashbus99** [comment]
> @trashbus99 Did you actually reconfigure the controllers and then exit out of the emulator? The config files literally show the same keymappings for before and after.

[qt-config_xb1.ini.txt](https://github.com/ordovice/batocera-switch/files/11556190/qt-config_xb1.ini.txt)

Sorry, Redid on v36.  Button plus now, for example, should show button 7 (it was 8 before)

**Comment by ordovice** [comment]
@trashbus99 Sorry I'm behind and just getting to this.  Something doesn't seem right with the qt-config as the GUID shows 060000005e040000120b00000d050000 which isn't in the gamecontrollerdb, so I want to make sure it's actually being generated by yuzu.  Can you re-run with autoconfig on and re-upload all 3 files?

**Comment by trashbus99** [comment]
[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/11664234/es_launch_stdout.log)
[qt-config.zip](https://github.com/ordovice/batocera-switch/files/11664242/qt-config.zip)

**Comment by ordovice** [comment]
I should've been more specific.  Run the auto config, then manually config your controller.  The two qt-config files are nearly identical.  I need the differences to see the proper encoding for the controller.

**Comment by trashbus99** [comment]
[qt-config.txt.zip](https://github.com/ordovice/batocera-switch/files/11664732/qt-config.txt.zip)

**Comment by trashbus99** [comment]
Same as after I ran uureels update script..qt-config here..

[qt-config txt](https://github.com/ordovice/batocera-switch/files/11691928/qt-config.txt)

 :-(

**Comment by trashbus99** [comment]
[qt-config.try2.txt](https://github.com/ordovice/batocera-switch/files/11692070/qt-config.try2.txt)

**Comment by trashbus99** [comment]
[3 files.zip](https://github.com/ordovice/batocera-switch/files/11692149/3.files.zip)
