### ISSUE TITLE
xbox series s|x controllers mappings messed up over bluetooth (xbox one 1709 was messed up too) v35

### ISSUE THREAD

**Issue by trashbus99** [ordovice/batocera-switch#63]
**List the Controllers you're using**

**Ryujinx**
Change the emulator to Ryujinx-Avalonia
Configure your controllers manually
Attach the following files to the bug report
- share\system\logs\es_launch_stdout.log
- share\system\configs\Ryujinx\BeforeRyu.json
- share\system\configs\Ryujinx\Config.json

**Additional context**
Add any other context about the problem here, such as "keys are reversed" or anything else you can provide
[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/10252367/es_launch_stdout.log)

[BeforeRyu.json,txt](https://github.com/ordovice/batocera-switch/files/10252365/BeforeRyu.json.txt)
[Config.json.txt](https://github.com/ordovice/batocera-switch/files/10252366/Config.json.txt)

Keys mappings are all over the place..

**Comment by trashbus99** [comment]
forgot to mention on v35

**Comment by ordovice** [comment]
@trashbus99 Did you actually configure the controllers?  The config files show the same information in both files for the keymappings.
