### ISSUE TITLE
SN30 - Pro Controller Mode (Y) - Detects as Switch Pro Controller

### ISSUE THREAD

**Issue by ordovice** [ordovice/batocera-switch#68]
**List the Controllers you're using**

**Yuzu**
Change the emulator to yuzu or yuzu-early-access
Configure your controllers manually
Attach the following files to the bug report
- share\system\logs\es_launch_stdout.log
- share\system\configs\yuzu\before-qt-config.ini
- share\system\configs\yuzu\qt-config.ini

**Additional context**
Add any other context about the problem here, such as "keys are reversed" or anything else you can provide
[before-qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/10262500/before-qt-config.ini.txt)
[qt-config.ini.txt](https://github.com/ordovice/batocera-switch/files/10262501/qt-config.ini.txt)
[es_launch_stdout.log](https://github.com/ordovice/batocera-switch/files/10262503/es_launch_stdout.log)

**Comment by drizzt** [comment]
Hi,
I have a similar issue with 8bitdo pro 2 in switch controller mode.

To use it with gyroscope on games that uses it (like Captain Toad) I have to disable autoconfig and enable pro driver (experimental) from yuzu config directly

**Comment by ordovice** [comment]
Please re-do this.  Can you please connect up ONLY the 8bitdo Pro2 in switch mode, run yuzu, then use Yuzus configuration to configure the buttons manually and then re-upload the files?

**Comment by drizzt** [comment]
Sure, consider that this also works for official Nintendo Switch Pro Controller and that I use the pro driver (experimental) or the gyroscope won't work correctly:

So, to recap:
```
enable_procon_driver=true
player_0_button_a="engine:joycon,guid:00000000000000000000000000000003,port:0,button:2048,pad:3"
player_0_button_b="engine:joycon,guid:00000000000000000000000000000003,port:0,button:1024,pad:3"
player_0_button_ddown="engine:joycon,guid:00000000000000000000000000000003,port:0,button:1,pad:3"
player_0_button_dleft="engine:joycon,guid:00000000000000000000000000000003,port:0,button:8,pad:3"
player_0_button_dright="engine:joycon,guid:00000000000000000000000000000003,port:0,button:4,pad:3"
player_0_button_dup="engine:joycon,guid:00000000000000000000000000000003,port:0,button:2,pad:3"
player_0_button_home="engine:joycon,guid:00000000000000000000000000000003,port:0,button:1048576,pad:3"
player_0_button_l="engine:joycon,guid:00000000000000000000000000000003,port:0,button:64,pad:3"
player_0_button_lstick="engine:joycon,guid:00000000000000000000000000000003,port:0,button:524288,pad:3"
player_0_button_minus="engine:joycon,guid:00000000000000000000000000000003,port:0,button:65536,pad:3"
player_0_button_plus="engine:joycon,guid:00000000000000000000000000000003,port:0,button:131072,pad:3"
player_0_button_r="engine:joycon,guid:00000000000000000000000000000003,port:0,button:16384,pad:3"
player_0_button_rstick="engine:joycon,guid:00000000000000000000000000000003,port:0,button:262144,pad:3"
player_0_button_screenshot="engine:joycon,guid:00000000000000000000000000000003,port:0,button:2097152,pad:3"
player_0_button_sl=[empty]
player_0_button_sr=[empty]
player_0_button_x="engine:joycon,guid:00000000000000000000000000000003,port:0,button:512,pad:3"
player_0_button_y="engine:joycon,guid:00000000000000000000000000000003,port:0,button:256,pad:3"
player_0_button_zl="engine:joycon,guid:00000000000000000000000000000003,port:0,button:128,pad:3"
player_0_button_zr="engine:joycon,guid:00000000000000000000000000000003,port:0,button:32768,pad:3"
player_0_connected=true
player_0_lstick="engine:joycon,guid:00000000000000000000000000000003,port:0,pad:3,axis_x:0,axis_y:1,deadzone:0.150000"
player_0_motionleft="engine:joycon,guid:00000000000000000000000000000003,port:0,pad:3,motion:0"
player_0_motionright="engine:joycon,guid:00000000000000000000000000000003,port:0,pad:3,motion:1"
player_0_rstick="engine:joycon,guid:00000000000000000000000000000003,port:0,pad:3,axis_x:2,axis_y:3,deadzone:0.150000"
player_0_type=0
player_0_vibration_enabled=true
player_0_vibration_strength=100
```

**Comment by ordovice** [comment]
@drizzt Can you follow the process for configuring the controller and grabbing me the 3 files with one controller connected?  Also, is this in v36 or v37?

**Comment by ordovice** [comment]
All mapping moved to SDL.  Closing this issue.
