### ISSUE TITLE
Launching Yuzu breaks Flatpak audio

### ISSUE THREAD

**Issue by NobleGaming** [ordovice/batocera-switch#7]
After launching yuzu audio will break on any program using flatpak (primarily steam) and there will be no sound only on flatpak until batocera is restarted. Dolphin used to have this issue in v33 and was fixed in v34 but yuzu still has the issue.

**Comment by ordovice** [comment]
Yuzu is an appimage that is compiled by the yuzu team, and this code is just python that wraps around it.  I'd suggest trying after I've updated and implemented a proper v34 version.

**Comment by ordovice** [comment]
Can you test the newest version of my code and newest version of yuzu?
