### ISSUE TITLE
V34 not work 

### ISSUE THREAD

**Issue by Lino77** [ordovice/batocera-switch#8]
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 8, in <module>
    from Evmapy import Evmapy
  File "/userdata/system/switch/configgen/Evmapy.py", line 8, in <module>
    import evdev
  File "/userdata/system/switch/configgen/evdev/__init__.py", line 7, in <module>
    from evdev.device import DeviceInfo, InputDevice, AbsInfo
  File "/userdata/system/switch/configgen/evdev/device.py", line 6, in <module>
    from evdev import _input, ecodes, util
  File "/userdata/system/switch/configgen/evdev/ecodes.py", line 44, in <module>
    from evdev import _ecodes
ImportError: cannot import name '_ecodes' from partially initialized module 'evdev' (most likely due to a circular import) (/userdata/system/switch/configgen/evdev/__init__.py)

**Comment by ordovice** [comment]
This is a known issue.  I am working on an updated version for v34.  I'll close this once I have a working version.

**Comment by foclabroc** [comment]
> Traceback (most recent call last): File "/userdata/system/switch/configgen/switchlauncher.py", line 8, in from Evmapy import Evmapy File "/userdata/system/switch/configgen/Evmapy.py", line 8, in import evdev File "/userdata/system/switch/configgen/evdev/**init**.py", line 7, in from evdev.device import DeviceInfo, InputDevice, AbsInfo File "/userdata/system/switch/configgen/evdev/device.py", line 6, in from evdev import _input, ecodes, util File "/userdata/system/switch/configgen/evdev/ecodes.py", line 44, in from evdev import _ecodes ImportError: cannot import name '_ecodes' from partially initialized module 'evdev' (most likely due to a circular import) (/userdata/system/switch/configgen/evdev/**init**.py)

Just delete "evdev" folder in /system/switch/configgen/

**Comment by ordovice** [comment]
Can you try the new version out?  It also autoconfigures controls in Yuzu.

**Comment by Lino77** [comment]
okay  testet with x86_64 - 34 2022/05/23  game Zelda  and it works
