### ISSUE TITLE
Add some more syslink to help users

### ISSUE THREAD

**Issue by Darknior** [ordovice/batocera-switch#91]
Hi

Why don't put the two directories **/saves/yuzu** and **/saves/Ryujinx** in the already existing **/saves/switch/switch** directory ??
```
/saves/switch/switch/yuzu
/saves/switch/switch/Ryujinx

```
And for real, only this directory has Yuzu saves : **/userdata/saves/yuzu/0000000000000000**

I think we also miss one syslink to make Switch easier to use

- Profiles are in a lost subdirectory, hard to found for a noob here,
`userdata/system/configs/yuzu/nand/system/save/8000000000000010/su/avators/`
Maybe it can be put in saves directory,
`/saves/switch/yuzu/profile`

**Comment by uureel** [comment]
no real need to move/merge saves locations as it's not an issue but might cause some issues, but with 37 samba now supporting symlinks i've added a symlink to yuzu's/./././././avators as /userdata/saves/yuzu/profile

**Comment by Darknior** [comment]
Yes i have seen, thanks a lot.

For the save directories yes it is not a problem, but configuen create the empty directory for nothing.: /saves/switch
It's why i have think to move the used directories on this one.

It is the same idea that one day we will must create a ubdirectory by CORE in SAVE directories, because for now the structure is false. A Snes9x savestate for exemple is not compatible with a Bsnes one, and ES dont know it and you can try to launch it and it will crash ....
