### ISSUE TITLE
joycons emulation is rotated

### ISSUE THREAD

**Issue by biGdada** [ordovice/batocera-switch#93]
**List the Controllers you're using**
DS4 controllers.

**Additional context**
while switching pad type to joycon, the controls are reversed. i checked the sources, and it seems like while changing the pad type the only thing happens is that the controller is reported as joycon and the button mappings stay the same, which effectively makes the buttons rotated 90 degrees.

i think you should consider remapping the buttons, or maybe add an option to rotate the controls.
An example of a game that is affected is Mario Party. It accepts only joycons, but you supposed to hold them horizontally.

**Comment by ordovice** [comment]
I will test.  One of the things I've been looking at is for v36 building a better database of buttons/configs which would allow this to be easy to accomodate.

**Comment by ordovice** [comment]
Still in the queue, just not a priority with work at the moment

**Comment by ordovice** [comment]
FYI: Mario Party superstars works with "Pro Controller".  I'll be sure to test the other Mario Party soon, as I now have a controller database so I can work on making joycons work as well.

**Comment by ordovice** [comment]
This is now set in Ryujinx Configgen and I will be updating the Yuzu Configgen next as I improve the mapping capabilities of it.

**Comment by ordovice** [comment]
This is now set in the Yuzu configgen.
